### ISSUE TITLE
Nonexisting DApp shows empty template

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#67] opened 2017-10-18 10:31 UTC
When I try to load a non-existing DApp I get an empty dapp template, instead I'd expect to get some kind of error message (also server side a 404 message for crawler purposes).

![screenshot 2017-10-18 12 29 25](https://user-images.githubusercontent.com/620959/31713928-2f8aa184-b400-11e7-8318-17b472f02e62.png)

**Comment by robyedlin** [comment] 2017-10-23 18:01
Correct status code should be 400, but that will impact the dapp lookup on the submit page, so this needs to be resolved first: https://github.com/state-of-the-dapps/sotd-www/issues/80

**Comment by jorisbontje** [comment] 2017-10-25 10:10
After the redirect I get the following stacktrace:
```
vue-router.esm.js:1832 TypeError: Cannot read property 'components' of undefined
    at i (google-analytics.plugin.76c7bae6.js:33)
    at google-analytics.plugin.76c7bae6.js:20
    at vue-router.esm.js:1926
    at Array.forEach (<anonymous>)
    at e.te.updateRoute (vue-router.esm.js:1925)
    at vue-router.esm.js:1802
    at vue-router.esm.js:1911
    at r (vue-router.esm.js:1649)
    at at (vue-router.esm.js:1660)
    at vue-router.esm.js:1906
```

**Comment by robyedlin** [comment] 2017-10-25 19:03
I can't reproduce. Is that error in the browser console, the server console, or the server log?

**Comment by jorisbontje** [comment] 2017-10-25 19:23
this happens in the Chrome browser console when I navigate to https://www.stateofthedapps.com/dapps/xxx
it doesn't happen localhost; probably related to the google-analytics plugin being activated.

**Comment by robyedlin** [comment] 2017-10-25 21:45
I will set up a stage on heroku for production related issues.

**Comment by robyedlin** [comment] 2017-10-25 21:57
Looks like a production mode issue, as google analytics is only initialized in production.

Can reproduce with:

`npm run build`
`npm run start`

Navigate to: http://localhost:3000/404

Seems to be a general 404 bug in the @nuxtjs/google-analytics module. Can we close this, log as an issue in Nuxt, and as a new issue in this repo?

**Comment by robyedlin** [comment] 2017-10-25 22:00
Related to: https://github.com/state-of-the-dapps/sotd-www/issues/92

**Closed** 2017-10-26 19:39 UTC
Labels: bug, scoped
